/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	resourcev1alpha3 "k8s.io/api/resource/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceSlicePatchLister helps list ResourceSlicePatches.
// All objects returned here must be treated as read-only.
type ResourceSlicePatchLister interface {
	// List lists all ResourceSlicePatches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceSlicePatch, err error)
	// ResourceSlicePatches returns an object that can list and get ResourceSlicePatches.
	ResourceSlicePatches(namespace string) ResourceSlicePatchNamespaceLister
	ResourceSlicePatchListerExpansion
}

// resourceSlicePatchLister implements the ResourceSlicePatchLister interface.
type resourceSlicePatchLister struct {
	listers.ResourceIndexer[*resourcev1alpha3.ResourceSlicePatch]
}

// NewResourceSlicePatchLister returns a new ResourceSlicePatchLister.
func NewResourceSlicePatchLister(indexer cache.Indexer) ResourceSlicePatchLister {
	return &resourceSlicePatchLister{listers.New[*resourcev1alpha3.ResourceSlicePatch](indexer, resourcev1alpha3.Resource("resourceslicepatch"))}
}

// ResourceSlicePatches returns an object that can list and get ResourceSlicePatches.
func (s *resourceSlicePatchLister) ResourceSlicePatches(namespace string) ResourceSlicePatchNamespaceLister {
	return resourceSlicePatchNamespaceLister{listers.NewNamespaced[*resourcev1alpha3.ResourceSlicePatch](s.ResourceIndexer, namespace)}
}

// ResourceSlicePatchNamespaceLister helps list and get ResourceSlicePatches.
// All objects returned here must be treated as read-only.
type ResourceSlicePatchNamespaceLister interface {
	// List lists all ResourceSlicePatches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceSlicePatch, err error)
	// Get retrieves the ResourceSlicePatch from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*resourcev1alpha3.ResourceSlicePatch, error)
	ResourceSlicePatchNamespaceListerExpansion
}

// resourceSlicePatchNamespaceLister implements the ResourceSlicePatchNamespaceLister
// interface.
type resourceSlicePatchNamespaceLister struct {
	listers.ResourceIndexer[*resourcev1alpha3.ResourceSlicePatch]
}
